#  SPDX-License-Identifier: BSD-3-Clause
#  Copyright (c) 2026 poweraid. All rights reserved.
#

SPDK_ROOT_DIR := $(abspath $(CURDIR)/../../../../../..)

TEST_FILE = poweraid_raid_common_mwl_ut.c

include $(SPDK_ROOT_DIR)/mk/spdk.unittest.mk
